#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

@parent_research = Research.find_by_title('Pesquisas.SegurancaPaisForm')
@parent_research = Research.create(:title => 'Pesquisas.SegurancaPaisForm', :introduction => 'Pesquisas.SegurancaPaisForm') if @parent_research.nil?

@young_research  = Research.find_by_title('Pesquisas.SegurancaJovensForm')
@young_research = Research.create(:title => 'Pesquisas.SegurancaJovensForm', :introduction => 'Pesquisas.SegurancaJovensForm') if @young_research.nil?

PESQUISA_JOVENS = %w[ 
Gnero
Estado
Idade
PrincipaisLocaisdeAcesso
HorasConectadoporDia
LimitedeTempoConectado
TempoDemaisConectado
PrincipaisAtividadesConectado
FotologouBlog
SitesdeRelacionamento
AmigosVirtuais
QuantosAnosAprendeuInternet
OndeAprendeuInternet
HabilidadeemRelaoaosPais
ConsideraoSobreInternet
SenteSeguro
MaiorRisco
AmigoJFoiIncomodadoPorAlgoNaInternet
JVivenciouOnline
AmigoJEncontrouPessoalmenteUmAmigoVirtual
ConsideraEncontrarPessoalmenteAmigoVirtual
PaisAcompanhamaNavegaonaInternet
OQueSenteQuandoMonitoramNavegao
ObdeceasRegrasdosPais
QuandoSeCastastraemSitedeRelacionamentooFaz
InformaesqueCompartilhanaInternet
InternetumBomLugarparaSeRelacionar
OQueAchaSobreMedidasAtuaisParaProtegerJovens
AchaQueAsInstituiesOuvemosJovensparaElaborarMedidas
TemasQueJDiscutiu
MeiosParaAprenderSobreRiscosDaInternet
MeiosEficazesParaAprenderSobreSegurananaInternet
EmRelaoaDivulgarDicasdeSegurana
JFoiVtima
AmigoJFoiVtima
JDenunciou
TipodeCrimeDenunciado
Email
GostariadeReceberOrientaesPorEmail
]

PESQUISA_PAIS = %w[
Gnero
Estado
Idade
QuantidadedeFilhosMenoresque18AnosqueUsamInternet
IdadedoFilhoqueMaisUsaInternet
PrincipaisLocaisdeAcesso
PrincipaisLocaisdeAcessodosFilhos
QuantoNavegaPorDia
QuantooFilhoNavegaPorDia
HLimiteproTempodeNavegaodosFilhos
PrincipaisAtividadesOnline
PrincipaisAtividadesOnlinedosFilhos
QuantosAmigosVirtuaisPossui
QuantosAmigosVirtuaisosFilhosPossuem
HabilidadeemRelaoaosFilhos
SenteSeguro
SentequeosFilhosestoSeguros
AcompanhaaNavegaodosFilhos
ReaodosFilhosQuandoMonitorados
MaiorRiscoparaosFilhos
FrequnciaqueosFilhosManifestamIncmodo
FilhosJForamVtimas
JFoiVtima
ConsideraEncontrarPessoalmenteumAmigoVirtual
PermitiriaqueoFilhoEncontrassePessoalmenteumAmigoVirtual
FilhoJEncontrouPessoalmenteumAmigoVirtual
AcompanhaQuandoFilhoSeCadastraemSitedeRelacionamento
InformaesqueosFilhosCompartilham
HabilidadeemManteraSeguranadosFilhosnaInternet
FilhosFicamTempoDemaisConectados
OrientaosFilhosemRelaoaInternet
RegrasInstituidas
FilhosObedecemRegras
MeiosEficazesParaAprenderSobreSegurana
EmRelaoaDivulgarDicas
JDenunciou
TipodeCrimequeDenunciou
ReceberOrientaes
Email
]

PESQUISA_JOVENS.each do |question|
  @young_research.items<< Item.create(:info => question)
end

PESQUISA_PAIS.each do |question|
  @parent_research.items<< Item.create(:info => question)
end


#Dir.glob('../data/twiki/SegurancaPais*').select do |filename|
pattern = '../data/twiki/*'
#puts Dir.glob('../data/twiki/*').inspect
#puts Dir.glob('../data/twiki/*').inspect

migrate_log = File.open('../data/migrate.log', 'w+')
log_files_processed = File.open('../data/files_processed.log', 'w+')

Dir.glob(pattern).each do |filename|
  next if filename.match(/.txt,v|PesquisaPaisForm.lease/)

  file = File.open(filename, 'r')

  migrate_log.write("TWiki File #{filename} open.\n")
  
  first_line = file.readline
  raise 'This line cannot be nil' if first_line.nil?
  log_filename = first_line.match(/META:TOPICINFO.*date=(.*) format.*/)[1]
  log_filename = log_filename.gsub('"','')

  migrate_log.write("The log filename should be: #{log_filename}\n")

  if log_filename.to_i < 1218822785   
    migrate_log.write("The TWiki topic #{filename} was probably created before the log creation\n")
    migrate_log.write("\n\n")
    next 
  end

  search_for_log = true
  count = 0
  log_file = nil
  while(search_for_log) do 
    begin
      log_file = File.open("../data/log/#{log_filename}", 'r')
       search_for_log = false
    rescue
      migrate_log.write("The file #{log_filename} was not found on log directory on search number #{count}.\n")
      count = count + 1
      log_filename = log_filename.to_i - 1
    end

    if count == 3
      migrate_log.write("DANGEROUS: There is no log file associated to twiki topic #{filename}.\n")
      break
    end 
  end

  unless log_file.nil?
    log_files_processed.write(log_file.path.split('/').last + "\n")
    next
  end
  
  log_file.readline # There is nothing on line 1.
  log_file.readline.split(':').last # Research name on line 2.
  log_file.readline # Nothing important on line 3.
  log_file.readline # Nothing important on line 4.
  log_file.readline # Nothing important on line 5.

  # Answers of users.
  log_file.readline # Nothing important on line 5.
  
  migrate_log.write("\n\n")
end


#Environment.delete_all
#Environment.create!(:is_default => true)

#User.delete_all
#User.create!(:login => 'leandro', :password => 'leandro', :password_confirmation => 'leandro', :email => 'leandronunes@safernet.org.br')
#User.create!(:login => 'admin', :password => '123456', :password_confirmation => '123456', :email => 'admin@safernet.org.br', :is_administrator => true)
