#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

@parent_research = Research.find_by_title('Pesquisas.SegurancaPaisForm')
@parent_research = Research.create(:title => 'Pesquisas.SegurancaPaisForm', :introduction => 'Pesquisas.SegurancaPaisForm') if @parent_research.nil?

@young_research  = Research.find_by_title('Pesquisas.SegurancaJovensForm')
@young_research = Research.create(:title => 'Pesquisas.SegurancaJovensForm', :introduction => 'Pesquisas.SegurancaJovensForm') if @young_research.nil?
PESQUISA_JOVENS = {
"Gnero" => "Gênero"
"Estado" => "Estado de residência"
"Idade" => "Sua idade"
"PrincipaisLocaisdeAcesso" => "Quais os seus 2 (dois) principais locais de acesso à internet?"
"HorasConectadoporDia" => "Quantas horas <strong>por dia</strong>, em média, você navega na internet?"
"LimitedeTempoConectado" => "Há algum limite de tempo para sua navegação na internet?"
"TempoDemaisConectado" => "Você acha que fica tempo demais na internet?"
"PrincipaisAtividadesConectado" => "Quais as suas 3 (três) atividades on-line preferidas?"
"FotologouBlog" => "Você possui Fotolog e/ou Blog?"
"SitesdeRelacionamento" => "Quais sites de relacionamento você acessa?"
"AmigosVirtuais" => "Quantos amigos virtuais (que conheceu pela internet) você possui?"
"QuantosAnosAprendeuInternet" => "Com quantos anos você começou a utilizar a internet?"
"OndeAprendeuInternet" => "Onde você aprendeu a utilizar a internet?"
"HabilidadeemRelaoaosPais" => "Você é mais habilidoso no uso da internet do que os seus pais?"
"ConsideraoSobreInternet" => "Sobre a internet, o que você mais concorda?"
"SenteSeguro" => "Você se sente seguro usando a internet?"
"MaiorRisco" => "Quais são os 3 (três) riscos mais prováveis quando você está on-line?"
"AmigoJFoiIncomodadoPorAlgoNaInternet" => "Algum amigo seu já contou que foi incomodado, agredido, envergonhado ou humilhado pela internet?"
"JVivenciouOnline" => "Qual destas situações você já vivenciou on-line?"
"AmigoJEncontrouPessoalmenteUmAmigoVirtual" => "Algum amigo seu já se encontrou pessoalmente com um amigo virtual (que conheceu pela internet)?"
"ConsideraEncontrarPessoalmenteAmigoVirtual" => "Você se encontraria pessoalmente com algum amigo virtual (que conheceu pela internet)?"
"PaisAcompanhamaNavegaonaInternet" => "Seus pais acompanham sua navegação na internet?"
"OQueSenteQuandoMonitoramNavegao" => "Quando eles monitoram sua navegação, o que você sente?"
"ObdeceasRegrasdosPais" => "Você obedece as regras que seus pais colocaram para seu uso da internet?"
"QuandoSeCastastraemSitedeRelacionamentooFaz" => "Quando você se cadastra em algum site de relacionamento, geralmente, o faz"
"InformaesqueCompartilhanaInternet" => "Que tipo de informações pessoais você compartilha pela internet?"
"InternetumBomLugarparaSeRelacionar" => "A internet é um ótimo lugar para aprender e fazer amigos?"
"OQueAchaSobreMedidasAtuaisParaProtegerJovens" => "O que você acha das medidas atualmente disponíveis para proteger as crianças e jovens na internet?"
"AchaQueAsInstituiesOuvemosJovensparaElaborarMedidas" => "Você acha que as instituições e os adultos ouvem os jovens para elaborar as dicas de proteção on-line?"
"TemasQueJDiscutiu" => "Em relação à segurança na internet, quais temas você já discutiu?"
"MeiosParaAprenderSobreRiscosDaInternet" => "Quais meios você já utilizou para aprender mais sobre prevenção na internet?"
"MeiosEficazesParaAprenderSobreSegurananaInternet" => "Quais são os 2 (dois) meios mais legais e práticos para aprender sobre segurança on-line?"
"EmRelaoaDivulgarDicasdeSegurana" => "Em relação ao trabalho de divulgação das dicas de segurança para proteger outras crianças na internet, você"
"JFoiVtima" => "Você já foi vítima de alguma das situações abaixo?"
"AmigoJFoiVtima" => "Algum amigo seu já foi vítima das situações abaixo?"
"JDenunciou" => "Você já denunciou algum crime que viu na internet?"
"TipodeCrimeDenunciado" => "Que tipo de crime denunciou?"
"GostariadeReceberOrientaesPorEmail" => "Gostaria de receber orientações por e-mail com mais dicas sobre proteção na internet?"
"Email" => "Email"
}

PESQUISA_PAIS = {
"Gnero" => "Gênero"
"Estado" => "Estado de residência"
"Idade" => "Sua idade"
"QuantidadedeFilhosMenoresque18AnosqueUsamInternet" => "Quantos filhos e/ou crianças menores de 18 anos sob sua responsabilidade usam a internet?"
"IdadedoFilhoqueMaisUsaInternet" => "Qual a idade do seu filho que mais utiliza a internet?"
"PrincipaisLocaisdeAcesso" => "Quais os SEUS 2 (dois) principais locais de acesso à internet?"
"PrincipaisLocaisdeAcessodosFilhos" => "Quais os <strong>2</strong> (dois) principais locais de acesso à internet de SEUS FILHOS?"
"QuantoNavegaPorDia" => "Quantas horas <strong>por dia</strong>, em média, VOCÊ navega na internet?"
"QuantooFilhoNavegaPorDia" => "Quantas horas <strong>por dia</strong>, em média, SEUS FILHOS navegam na internet?"
"HLimiteproTempodeNavegaodosFilhos" => "Há algum limite de tempo para SEUS FILHOS usarem a internet?"
"PrincipaisAtividadesOnline" => "Quais as SUAS <strong>2</strong> (duas) atividades on-line preferidas?"
"PrincipaisAtividadesOnlinedosFilhos" => "Quais as <strong>2</strong> (duas) atividades on-line preferidas de SEUS FILHOS?"
"QuantosAmigosVirtuaisPossui" => "Quantos amigos virtuais (que conheceu pela internet) VOCÊ possui?"
"QuantosAmigosVirtuaisosFilhosPossuem" => "Quantos amigos virtuais (que conheceu pela internet) SEUS FILHOS possuem?"
"HabilidadeemRelaoaosFilhos" => "Como você compara sua habilidade de utilização da internet  com relação a do seus filhos?"
"SenteSeguro" => "VOCÊ se sente seguro usando a internet?"
"SentequeosFilhosestoSeguros" => "Você sente que SEUS FILHOS estão seguros quando usam a internet?"
"AcompanhaaNavegaodosFilhos" => "Você acompanha a navegação de seus filhos?"
"ReaodosFilhosQuandoMonitorados" => "Quando monitora a navegação dos filhos, quais as principais reações deles?"
"MaiorRiscoparaosFilhos" => "Quais você considera os 3 (três) riscos mais prováveis que seus filhos correm quando estão on-line?"
"FrequnciaqueosFilhosManifestamIncmodo" => "Quantas vezes seus filhos já manifestaram incômodo ou constrangimento por algo que viram ou vivenciaram pela internet?"
"FilhosJForamVtimas" => "Seu filho já foi vítima de alguma das situações abaixo?"
"JFoiVtima" => "Você já foi vítima de alguma das situações abaixo?"
"ConsideraEncontrarPessoalmenteumAmigoVirtual" => "VOCÊ encontraria pessoalmente alguém que conheceu pela internet?"
"PermitiriaqueoFilhoEncontrassePessoalmenteumAmigoVirtual" => "Você permitiria SEUS FILHOS se encontrarem pessoalmente com alguém que conheceram pela internet?"
"FilhoJEncontrouPessoalmenteumAmigoVirtual" => "Um de seus filhos já se encontrou pessoalmente com alguém que conheceu pela internet?"
"AcompanhaQuandoFilhoSeCadastraemSitedeRelacionamento" => "Quando SEUS FILHOS se cadastram em algum site de relacionamento você os acompanha?"
"InformaesqueosFilhosCompartilham" => "Que tipo de informações pessoais você sabe que SEUS FILHOS compartilham pela internet?"
"HabilidadeemManteraSeguranadosFilhosnaInternet" => "Como você avalia SUA habilidade para manter a segurança de seus filhos na internet?"
"FilhosFicamTempoDemaisConectados" => "Você acha que  SEUS FILHOS ficam tempo demais conectados à internet?"
"OrientaosFilhosemRelaoaInternet" => "Você orienta  SEUS FILHOS em relação aos perigos e comportamentos impróprios na internet?"
"RegrasInstituidas" => "Quais das regras abaixo você instituiu para prevenir a navegação de  SEUS FILHOS?"
"FilhosObedecemRegras" => "Você considera que SEUS FILHOS obedecem suas regras quando usam a internet?"
"MeiosEficazesParaAprenderSobreSegurana" => "Quais os 3 (três) meios mais eficazes e práticos para você aprender dicas sobre segurança na internet que servirão para seus filhos?"
"EmRelaoaDivulgarDicas" => "Em relação ao trabalho de divulgação de dicas de segurança para proteger outras crianças na internet você"
"JDenunciou" => "Você já denunciou algum crime que viu na internet?"
"TipodeCrimequeDenunciou" => "Que tipo de crime denunciou?"
"ReceberOrientaes" => "Gostaria de receber orientações por e-mail sobre segurança e proteção das crianças na internet?"
"Email" => "Email"
}

#Dir.glob('../data/twiki/SegurancaPais*').select do |filename|
pattern = '../data/twiki/*'
#puts Dir.glob('../data/twiki/*').inspect
#puts Dir.glob('../data/twiki/*').inspect

migrate_log = File.open('../data/migrate.log', 'w+')
log_files_processed = File.open('../data/files_processed.log', 'w+')

Dir.glob(pattern).each do |filename|
  next if filename.match(/.txt,v|PesquisaPaisForm.lease/)

  file = File.open(filename, 'r')

  migrate_log.write("TWiki File #{filename} open.\n")
  
  first_line = file.readline
  raise 'This line cannot be nil' if first_line.nil?
  log_filename = first_line.match(/META:TOPICINFO.*date=(.*) format.*/)[1]
  log_filename = log_filename.gsub('"','')

  migrate_log.write("The log filename should be: #{log_filename}\n")

  if log_filename.to_i < 1218822785   
    migrate_log.write("The TWiki topic #{filename} was probably created before the log creation\n")
    migrate_log.write("\n\n")
    next 
  end

  search_for_log = true
  count = 0
  log_file = nil
  while(search_for_log) do 
    begin
      log_file = File.open("../data/log/#{log_filename}", 'r')
       search_for_log = false
    rescue
      migrate_log.write("The file #{log_filename} was not found on log directory on search number #{count}.\n")
      count = count + 1
      log_filename = log_filename.to_i - 1
    end

    if count == 3
      migrate_log.write("DANGEROUS: There is no log file associated to twiki topic #{filename}.\n")
      break
    end 
  end

  unless log_file.nil?
    log_files_processed.write(log_file.path.split('/').last + "\n")
    next
  end
  
  log_file.readline # There is nothing on line 1.

  research_name = log_file.readline.split(':').last # Research name on line 2.
  research = research_name == @parent_research.title ? @parent_research : @young_research
  
  log_file.readline # Nothing important on line 3.
  log_file.readline # Nothing important on line 4.
  log_file.readline # Nothing important on line 5.

  # Answers of users.
  log_file.readlines.each do |answer|
  end
  
  migrate_log.write("\n\n")
end


#Environment.delete_all
#Environment.create!(:is_default => true)

#User.delete_all
#User.create!(:login => 'leandro', :password => 'leandro', :password_confirmation => 'leandro', :email => 'leandronunes@safernet.org.br')
#User.create!(:login => 'admin', :password => '123456', :password_confirmation => '123456', :email => 'admin@safernet.org.br', :is_administrator => true)
